### ISSUE TITLE
Sanitize schematic names

### ISSUE THREAD

**Issue by MrRar** [blockexchange/blockexchange_server#679]
The names of schematic files in the server are not restricted. It is possible to upload a file .we which creates a schematic with an empty name on the server. There is also no length limit to the name. Names can also include characters that cause problems for example if you name a schematic "../../search" it goes to the search page when you try to view it.

I would recommend limiting the names to be between 1 and 20 characters and they can only include upper and lower case letters, numbers and a few symbols. Maybe ban names that might cause problems like ".." and "."

**Comment by BuckarooBanzay** [comment]
fixed with 9ec7cde09fff02f7adbc8dfdd4f0ab91fea05f2c
