### ISSUE TITLE
Search not working as expected

### ISSUE THREAD

**Issue by TangentFoxy** [blockexchange/blockexchange_server#954]
I opened up search, typed "spathi eluder" and pressed enter, and this error appeared:
```json
{
  "message": "pq: syntax error in tsquery: \"spathi eluder\"",
  "status": 500
}
```

Also it appeared misplaced over the search button, making it hard to notice.

![image](https://github.com/user-attachments/assets/d7e7a248-50a5-4ed7-8faa-5567eed81d85)

It seems this error is that search isn't finding items named "Spathi_Eluder" when searching "spathi eluder". I don't know how search is working behind the scenes, but I'd expect this to work.

**Comment by BuckarooBanzay** [comment]
should be fixed, thanks for reporting :+1:
